[build]
  command = "npm run build"
  publish = "build"

[context.production]
  command = "npm run build:production"
  publish = "build"

[context.branch-deploy]
  command = "npm run build:branch-deploy"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
